all: SerialPi.class Pi.class Hello.class PrintArray.class SumArray.class SerialPrimes.class Primes.class DiningPhil.class ProdConDriver.class

SerialPi.class: SerialPi.java
	javac SerialPi.java

Pi.class: Pi.java
	javac Pi.java

Hello.class: Hello.java
	javac Hello.java

PrintArray.class: PrintArray.java
	javac PrintArray.java

SumArray.class: SumArray.java
	javac SumArray.java

SerialPrimes.class: SerialPrimes.java
	javac SerialPrimes.java

Primes.class: Primes.java
	javac Primes.java

DiningPhil.class: DiningPhil.java
	javac DiningPhil.java

ProdConDriver.class: ProdConDriver.java
	javac ProdConDriver.java

.PHONY: clean

clean:
	rm *.class
